Carousel
secompufscar/site-secomp-vue pull request #4
Opened 2020-10-17 02:46 UTC by eduardo-gualberto

Cria o componente do carousel (aqui criei um pra mobile, com diferentes dimensões de imagens, e outro para telas maiores) e o adiciona a home page, acima dos itens que já estavam lá.

2020-10-18 18:02 UTC, 18argon requested changes
Adicionei comentários nas partes em que acho necessário fazer alterações.

2020-10-19 14:03 UTC, eduardo-gualberto commented on src/App.vue
> +.phone-hidden {
redundante

2020-10-19 14:03 UTC, eduardo-gualberto commented on src/components/Carousel.vue
> +      <b-carousel interval="3000" indicators>
ok

2020-10-19 14:03 UTC, eduardo-gualberto commented on src/main.js
> +  BootstrapVue, CarouselPlugin, BadgePlugin, ButtonPlugin,
ok

2020-10-19 14:04 UTC, eduardo-gualberto commented on src/views/Home.vue
> +    carousel: CarouselComponent,
ok

2020-10-19 15:21 UTC, 18argon approved these changes
Ok

2020-10-23 03:50 UTC, merged