Add single event page, update favicon
secompufscar/site-secomp-vue pull request #5
Opened 2020-10-18 17:36 UTC by CptSpookz

2020-10-19 02:05 UTC, 18argon requested changes
Encontrei alguns problemas com a renderização do markdown por causa da reatividade do Vue e algumas correções para o linter.

2020-10-19 02:05 UTC, 18argon commented on src/views/EventView.vue
> +        this.event.dateTime = formatDate(this.dateTime);
Eu normalmente uso uma computed property quando é preciso fazer alguma modificação no dado original. Mas sei lá, acho que meio que tanto faz nesse caso.

2020-10-19 02:05 UTC, 18argon commented on src/views/EventView.vue
> +h2, h6 {
Dá para usar o text-center e text-justify do bootstrap também.

2020-10-19 14:21 UTC, eduardo-gualberto commented on src/views/EventView.vue
> +      event: {},
tem com this.$set, mas acredito que simplesmente reatribuir o objeto também funcione. O problema da atribuição com a reatividade está nos literais (ex.: string, number, let, var, etc.)

2020-10-19 14:22 UTC, eduardo-gualberto commented on src/views/EventView.vue
> +        <div v-if="!loading" class="content-loaded">
pode ser usado um v-else nesse caso

2020-10-19 15:16 UTC, 18argon commented on src/views/EventView.vue
> +        <div v-if="!loading" class="content-loaded">
Estava pensando em modificar a condição do v-if que já existe para "!loading && !error" e adicionar outro bloco em baixo com v-if "!loading && error", não gosto muito do v-else kkk, e teria que adidionar umas keys tbm se for usar um div no outro bloco. E um v-else nesse caso mostraria quando está carregando tbm, teria que mudar os três para v-if, v-else-if, v-else.

2020-10-21 00:04 UTC, 18argon approved these changes
Ok

2020-10-23 03:38 UTC, merged